export const states = [
  { en: "ANDHRA PRADESH", hi: "आंध्र प्रदेश" },
  { en: "ARUNACHAL PRADESH", hi: "अरुणाचल प्रदेश" },
  { en: "BIHAR", hi: "बिहार" },
  { en: "CHHATTISGARH", hi: "छत्तीसगढ़" },
  { en: "GOA", hi: "गोवा" },
  { en: "GUJARAT", hi: "गुजरात" },
  { en: "HARYANA", hi: "हरियाणा" },
  { en: "HIMACHAL PRADESH", hi: "हिमाचल प्रदेश" },
  { en: "JHARKHAND", hi: "झारखंड" },
  { en: "KARNATAKA", hi: "कर्नाटक" },
  { en: "KERALA", hi: "केरल" },
  { en: "ASSAM", hi: "असम" },
  { en: "MADHYA PRADESH", hi: "मध्य प्रदेश" },
  { en: "MAHARASHTRA", hi: "महाराष्ट्र" },
  { en: "MANIPUR", hi: "मणिपुर" },
  { en: "MEGHALAYA", hi: "मेघालय" },
  { en: "MIZORAM", hi: "मिज़ोरम" },
  { en: "NAGALAND", hi: "नागालैंड" },
  { en: "ODISHA", hi: "ओड़िशा" },
  { en: "PUNJAB", hi: "पंजाब" },
  { en: "RAJASTHAN", hi: "राजस्थान" },
  { en: "SIKKIM", hi: "सिक्किम" },
  { en: "TAMIL NADU", hi: "तमिल नाडु" },
  { en: "TELANGANA", hi: "तेलंगाना" },
  { en: "TRIPURA", hi: "त्रिपुरा" },
  { en: "UTTARAKHAND", hi: "उत्तराखंड" },
  { en: "UTTAR PRADESH", hi: "उत्तर प्रदेश" },
  { en: "WEST BENGAL", hi: "पश्चिम बंगाल" }
];
